name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (format: v0.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate version
        id: validate
        run: |
          VERSION=${{ github.event.inputs.version }}
          if ! [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version $VERSION is not in a valid format!"
            exit 1
          fi
          echo "::set-output name=version::$VERSION"

      - name: Run compile script
        run: |
          ./compile.sh ${{ steps.validate.outputs.version }}

      - name: Create Git tag
        run: |
          git config --local user.email "niclas.haderer.dev@gmail.com"
          git config --local user.name "Niclas Haderer"
          git tag -a ${{ steps.validate.outputs.version }} -m "Release ${{ steps.validate.outputs.version }}"
          git push origin --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.validate.outputs.version }}
          release_name: Release ${{ steps.validate.outputs.version }}
          draft: false
          prerelease: false
          files: bin/*
